apiVersion: v1
kind: Service
metadata:
    name: nodeexpresswebapp-service
spec:
    type: NodePort
    ports:
        - targetPort: 8080
          port: 80
          nodePort: 30002
    selector:
        release: beta
        type: poc